MY_DB_USER = 'djangodb'
MY_DB_PASSWORD = '123'
MY_STATIC_URL = 'https://s3.amazonaws.com/heroku-ynotserious/'
MY_AWS_ACCESS_KEY_ID = 'AKIAJXYF4KB32T2RHF3A'
MY_AWS_SECRET_ACCESS_KEY = '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'
MY_AWS_STORAGE_BUCKET_NAME = 'heroku-ynotserious'